# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-01 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_details', '0009_auto_20171024_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now=True)),
                ('Income', models.FloatField(default=0.0)),
                ('Expenditure', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation_grants',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Organisation_name', models.CharField(max_length=200)),
                ('Organisation_phno', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=300)),
                ('Amount', models.FloatField(default=0.0)),
                ('Date', models.DateField(auto_now=True)),
            ],
        ),
    ]
