# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-14 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_details', '0013_auto_20171102_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='Animal_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
