# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_details', '0014_animal_animal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourists',
            name='Phone_number',
            field=models.CharField(max_length=100),
        ),
    ]
